### ISSUE TITLE
Missing Code Coverage

### ISSUE THREAD

**Issue by adstep** [FountainJS/generator-fountain-angular1#65] opened 2016-10-04 05:30 UTC
Tests are running, coverage is built, but no files show in the coverage report.

Node.js v6.2.1
win32 10.0.14936
yo 1.8.5
npm 3.9.0

.yo-rc.json
{
  "generator-fountain-angular1": {
    "version": "1.0.0-rc1",
    "props": {
      "resolved": "C:\\Users\\adstep\\AppData\\Roaming\\npm\\node_modules\\generator-fountain-angular1\\generators\\app\\index.js",
      "namespace": "fountain-angular1:app",
      "argv": {
        "remain": [],
        "cooked": [],
        "original": []
      },
      "framework": "angular1",
      "modules": "webpack",
      "css": "scss",
      "js": "typescript",
      "ci": [],
      "sample": "hello",
      "router": "uirouter"
    }
  }
}

**Comment by micaelmbagira** [comment] 2016-10-04 11:42
Duplicate of https://github.com/FountainJS/generator-fountain-webapp/issues/39

**Closed by micaelmbagira** 2016-10-04 11:42 UTC
